### ISSUE TITLE
web.form.Checkbox.get_value() gives wrong results

### ISSUE THREAD

**Issue by tuomas2** [webpy/webpy#273]
web.form.Checkbox.get_value() gives always False, whether checkbox is checked or not.

I know that I can obtain correct results by looking at web.input() dictionary and checking if checkbox object is there. But this is not very conventional, and it would be most intuitive if get_value() would do this lookup for me. Is there any reason why it could not be that way?

**Comment by veprbl** [comment]
I see this issue in my tests. Checkbox'es also don't retain their value after form re-rendering.

**Comment by iredmail** [comment]
Issue closed due to no sample code snippet to reproduce the issue.

**Comment by lujoamel4** [comment]
I was having trouble with that. But it really is not a mistake.
If you run 
`form.Checkbox ('Monday', description = "Monday")`
webpy will show:
```
<th>
<label for = "Monday"> Monday </label>
</th>
<td> <input id = "monday" name = "monday" type = "checkbox" value>
<td>

```
After submitting the form, Monday's input value will be None, so in python bool (None) == False.

I think webpy should render something like this:
```
<th>
<label for = "Monday"> Monday </label>
</th>
<td> <input id = "monday" name = "monday" type = "checkbox" value = "1">
<td>

```
when no value is set because bool ("1") == True.

If someone is currently having this issue, can fix it by coding 
`form.Checkbox (' Monday ', description =' Monday ', value = "1")`

If the moderators agree, I could do a PR next week.

**Comment by iredmail** [comment]
> If you run `form.Checkbox ('Monday', description = "Monday")`
> webpy will show:
> ...
> `<td> <input id = "monday" name = "monday" type = "checkbox" value>`

Your Python code doesn't specify attribute `value` at all, so it's empty value. Try this:

```
form.Checkbox("Monday", value="monday")
```
