### ISSUE TITLE
web.go invalid syntax Template traceback

### ISSUE THREAD

**Issue by liuaifu** [webpy/webpy#346]
I have use jquery in my template file, and receive the following error:
web.go invalid syntax Template traceback

I take many time search in google, but no result for me. finally, i take a look the document in http://webpy.org, i see use $$ can output $, and solved my problem.

The template compiler not print exact line number, can improved?

`````` javascript
<script src="http://libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script language="javascript">
    function onRefreshStatus() {
        $("#status").load("/status");
    }
    $(document).ready(function() {
        setInterval(onRefreshStatus, 1000);
        //......
    });
</script>```
``````

**Comment by edwardsun9** [comment]
I also met this issue before. But i think write JavaScript code in HTML directly is not a good practice unless it's just for toy project.
And other better solution is you can try to use third party template engine instead of the default one (frankly, i really sick of the grammar). One good choice is Jinja2, you can find it from [here](http://jinja.pocoo.org/docs/dev/) and there is also an office tutorial for it from [here](http://webpy.org/cookbook/template_jinja)

**Comment by busilogic** [comment]
I use jQuery instead of $$ so the code is portable.
Ex: jQuery('id').val();

**Comment by anandology** [comment]
Use `$$` as suggested by @busilogic,
