### ISSUE TITLE
Max Concurrent Requests to 10

### ISSUE THREAD

**Issue by segator** [webpy/webpy#358]
I don't now if is a bug or it can be configured but by default
the max concurrent requests is 10 and I need atless 100

do you know how to configure it?

Thanks

**Comment by LiberiFatali** [comment]
I'm curious, too

**Comment by sandeep06011991** [comment]
Not possible without editing the source code . If you want to increase number of concurrent connections . I see 2 bottlenecks . Increase number of worker threads (10 min ) / request queue size (5) . Once the worker threads are exhausted there is code for growing and shrinking but i think this is broken  . Considering that as we increase the degree of multi threading the performance decreases due to switching overload . I would increase the size of request queue .  
@anandology Sir , Would be honored if you could point out any error in my approach ,  code understanding or communication as I am a newbie just getting started .

**Comment by anandology** [comment]
Is this for the built-in webserver? If so, I don't think that is meant for production use. You can use try fastcgi, gunicorn, uwsgi etc.

**Comment by MarlonAbeykoon** [comment]
They say for production use we need to use FastCGI with lighttpd. 

> FastCGI with lighttpd is the recommended way of using web.py in production. reddit.com handles millions of hits this way.

[http://webpy.org/install](check this)
